name: Moderate Profanity

on:
  discussion_comment:
    types: [created, edited]

permissions:
  discussions: write

jobs:
  filter:
    runs-on: ubuntu-latest
    steps:
      - uses: IEvangelist/profanity-filter@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          replacement-strategy: Emoji
